import React from 'react';
import { KanbanComponent, ColumnsDirective, ColumnDirective } from '@syncfusion/ej2-react-kanban';
import '../../styles/index.css';

const KanbanBoard = () => {
  let data = [
    { Id: 1, Status: 'Open', Summary: 'Analyze the new requirements gathered from the customer.', Type: 'Story', Priority: 'Low', Tags: 'Analyze,Customer', Estimate: 3.5, Assignee: 'Nancy Davloio', RankId: 1 },
    { Id: 2, Status: 'InProgress', Summary: 'Fix the issues reported in the IE browser.', Type: 'Bug', Priority: 'Release Breaker', Tags: 'IE', Estimate: 2.5, Assignee: 'Janet Leverling', RankId: 2 },
    { Id: 3, Status: 'InReview', Summary: 'Fix the issues reported by the customer.', Type: 'Bug', Priority: 'Low', Tags: 'Customer', Estimate: '3.5', Assignee: 'Steven walker', RankId: 1 },
    { Id: 4, Status: 'Close', Summary: 'Arrange a web meeting with the customer to get the login page requirements.', Type: 'Others', Priority: 'Low', Tags: 'Meeting', Estimate: 2, Assignee: 'Michael Suyama', RankId: 1 },
    { Id: 5, Status: 'InReview', Summary: 'Validate new requirements', Type: 'Improvement', Priority: 'Low', Tags: 'Validation', Estimate: 1.5, Assignee: 'Robert King', RankId: 1 },
  ];

  React.useEffect(() => {
    // Function to remove the specific auto-generated license-warning div
    const removeAutoGeneratedDiv = () => {
      const autoGeneratedDiv = document.querySelector('div[style*="position: fixed;"][style*="top: 10px;"][style*="left: 10px;"]');
      if (autoGeneratedDiv) {
        autoGeneratedDiv.remove();
      }
    };

    removeAutoGeneratedDiv();

    const observer = new MutationObserver(() => {
      removeAutoGeneratedDiv();
    });

    observer.observe(document.body, { childList: true, subtree: true });
    return () => observer.disconnect();
  }, []);

  return (
    <div>
      <div className="App">
        <KanbanComponent id="kanban" keyField="Status" dataSource={data} cardSettings={{ contentField: 'Summary', headerField: 'Id' }}>
          <ColumnsDirective>
            <ColumnDirective headerText="To Do" keyField="Open" />
            <ColumnDirective headerText="In Progress" keyField="InProgress" />
            <ColumnDirective headerText="In Review" keyField="InReview" />
            <ColumnDirective headerText="Done" keyField="Close" />
          </ColumnsDirective>
        </KanbanComponent>
      </div>
    </div>
  );
};

export default KanbanBoard;
